name: iOS starter workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
      - uses: actions/checkout@v2
      - name: Force Xcode 13.2.1
        run: sudo xcode-select -switch /Applications/Xcode_13.2.1.app
      - name: Build
        run: xcodebuild clean test -project "wifiCrack.xcodeproj" -scheme "Connected-Wifi-Information" -destination "platform=iOS Simulator,name=iPhone 12 Pro,OS=latest" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
      - name: Run tests
        run: xcodebuild clean test -project "wifiCrack.xcodeproj" -scheme "Connected-Wifi-Information" -destination "platform=iOS Simulator,name=iPhone 12 Pro,OS=latest" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
      
env:
   DEVELOPER_DIR: /Applications/Xcode_13.2.1.app/Contents/Developer
      
